#!/usr/bin/env bash
# retouch-mp3-files-by-name -- Retouch mp3 files in a reverse order by name
# 
# The first in lexicographic order should become the latest one, and the last
# the oldest one for a Podcast list, which typically displays in reverse
# chronological order, to display them correctly.
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-10-30
set -eu

# usage?
[ $# -gt 0 ] || { sed -n '1,/^#$/ s/^# //p' <"$0"; exit 1; }

# use the mid value of mtimes
oldest=`ls -tr "$@" | head -n 1`
latest=`ls -t  "$@" | head -n 1`
t1=`date -r "$oldest" +%s`
t2=`date -r "$latest" +%s`
t=$(((t1+t2)/2))

# XXX to stabilize the time, using either end is a better idea
t=$t1

CCYYMMDDhhmm() { perl -MDate::Format -e 'print time2str("%Y%m%d%H%M.%S", '"$1"')'; }
find "$@" | sort | while read -r f; do
    tt=`CCYYMMDDhhmm $t`
    ( set -x; touch -t "$tt" "$f" ) || true
    let t+=60
done
