#!/usr/bin/env bash
# update-filecasts -- Update all filecasts
# Usage: update-filecasts FILENAME [PATH..]
#  where
#   FILENAME is the name of the filecast file, e.g. podcast.rss
#   PATH is the parent (or ancestor) directory of filecast files
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-09-03

usage() {
    c=$?
    sed -n '2,/^#$/p' <"$0"
    exit $c
}

rssFileName=$1; shift || usage

find "${@:-.}" -name $rssFileName |
while read p; do
    (
    set -e
    cd "`dirname "$p"`"
    if [ -e .filecast.nested ]; then 
        find * -type d -execdir [ -e {}/.filecast.prune ] \; -prune -o -print0 |
        xargs -0 filecasting
    elif [ . -nt $rssFileName ]; then
        filecasting *
    fi >.$rssFileName
    mv -f .$rssFileName $rssFileName
    )
done
